### ISSUE TITLE
create release

### ISSUE THREAD

**Issue by lifeofguenter** [infertux/munin-bitcoin#2]
would be nice if you could create a release so I can predictably deploy it :)

**Comment by infertux** [comment]
I don't think the existing plugins will see many changes in the future. If they do, I'll try to keep them backward compatible so existing configs won't break.

I agree it'd be nice to have proper releases but I don't want to burden myself with that until more people use these plugins. If you want to be a co-maintainer of the repo though, I'd happily give you admin rights, just let me know :)

**Comment by lifeofguenter** [comment]
I did not mean anything toooo complicated, but as simple as tagging the current master would already help a lot. That way $user can always predictably download the tagged version and know the code will not change - as opposed to setting his scripts to download master.

In any case, I hope its alright that I directly integrated it into my ansible-role: https://github.com/lifeofguenter/ansible-role-bitcoin-core :)

> admin rights, just let me know :)

Sure, why not :) - thanks!

**Comment by infertux** [comment]
The thing is I switched to [collectd](https://collectd.org/) so I don't think I'll keep updating these Munin plugins. I just gave you admin rights so you can `git tag` and take over the repo :D

> In any case, I hope its alright that I directly integrated it into my ansible-role: https://github.com/lifeofguenter/ansible-role-bitcoin-core :)

Very nice to see an Ansible role for this! Sameless plug, I did the same thing for [Chef](https://chef.io/): https://github.com/infertux/chef-bitcoin ;)
